[toolchain]
channel = "1.73.0" # See workspace Cargo.toml
components = ["rust-src", "rust-analyzer"]
profile = "default"
targets = ["x86_64-pc-windows-msvc", "aarch64-apple-darwin", "aarch64-linux-android"]
