[toolchain]
channel = "1.72.0" # See workspace Cargo.toml
components = ["rust-src", "rust-analyzer"]
profile = "default"
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc", "aarch64-linux-android"]
