name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check --all

  check:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install nix
        uses: cachix/install-nix-action@v22
      - name: Set up nix cache
        uses: cachix/cachix-action@v12
        continue-on-error: true
        with:
          name: nexus-ci
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Clippy lints
        run: |
          nix develop -ic \
            cargo clippy --all --all-features --all-targets --no-deps -- -Dwarnings
      - name: Cargo Doc
        run: |
          nix develop -ic \
            cargo doc --all --all-features --no-deps --document-private-items -- -Dwarnings
      - name: Cargo Test
        run: |
          nix develop -ic \
            cargo test --all --all-features --all-targets -- -Dwarnings
